enemy_color: "red"
# enemy_color: "blue"

#####-----神经网络参数-----#####
yolo_name: yolov5
classify_model: assets/tiny_resnet.onnx
yolo11_model_path: assets/yolo11.xml
yolov8_model_path: assets/yolov8.xml
yolov5_model_path: assets/yolov5.xml
device: GPU
min_confidence: 0.8
use_traditional: true

#####-----ROI-----#####
roi: 
  x: 420
  y: 50
  width: 600
  height: 600

use_roi: false

#####-----传统方法参数-----#####
threshold: 150
max_angle_error: 45 # degree
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20
min_lightbar_length: 8
min_armor_ratio: 1
max_armor_ratio: 5
max_side_ratio: 1.5
max_rectangular_error: 25 # degree

#####-----tracker参数-----#####
min_detect_count: 5
max_temp_lost_count: 15
outpost_max_temp_lost_count: 75

#####-----aimer参数-----#####
yaw_offset: -1 # degree -2.5
pitch_offset: -1.4 # degree 2
comming_angle: 60 # degree
leaving_angle: 20 # degree
decision_speed: 8 # rad/s
high_speed_delay_time: 0.030 # s
low_speed_delay_time: 0.015 # s

#####-----shooter参数-----#####
first_tolerance: 3 # 近距离射击容差，degree
second_tolerance: 2 # 远距离射击容差，degree
judge_distance: 2 #距离判断阈值
auto_fire: true # 是否由自瞄控制射击

camera_name: "hikrobot"
exposure_ms: 3
gain: 10.0
vid_pid: "2bdf:0001"

#  1  0  0
#  0  1  0
#  0  0  1
R_gimbal2imubody: [1, 0, 0, 0, 0, 1, 0, 1, 0]

# 重投影误差: 0.0867px
camera_matrix: [1779.800570778375, 0, 699.9109078038158, 0, 1781.3047749110701, 520.39241684723549, 0, 0, 1]
distort_coeffs: [-0.21139489573123771, 0.16401622887431042, -0.0011870788389302274, -4.5796284652329295e-05, 0]

# 相机同理想情况的偏角: yaw-161.21 pitch69.16 roll-72.39 degree
# 标定板到世界坐标系原点的水平距离: 0.52 m
# 标定板同竖直摆放时的偏角: yaw49.79 pitch64.08 roll136.82 degree
R_camera2gimbal: [0.9407542559576777, 0.039488610285080841, -0.33678194659938171, -0.00064691778647612457, 0.99340317719227644, 0.11467218076616324, 0.33908850082964093, -0.1076604718642971, 0.93457381270987006]
t_camera2gimbal: [-0.044244503258666253, -0.054091374365172126, 0.12978351893874365]

#####-----cboard参数-----#####
quaternion_canid: 0x100
bullet_speed_canid: 0x101
send_canid: 0xff
can_interface: "can0"

#####-----gimbal参数-----#####
com_port: "/dev/gimbal"
yaw_kp: 0
yaw_kd: 0
pitch_kp: 0
pitch_kd: 0

#####-----planner-----#####
fire_thresh: 0.0035

max_yaw_acc: 50
Q_yaw: [9e6, 0]
R_yaw: [1]

max_pitch_acc: 100
Q_pitch: [9e6, 0]
R_pitch: [1]

#####-----buff_detector参数-----#####
model: "assets/yolo11_buff_int8.xml"

#####-----buff_aimer参数-----#####
fire_gap_time: 0.700   # s
predict_time: 0.120     # s