enemy_color: "red"
# enemy_color: "blue"

#####-----神经网络参数-----#####
yolo_name: yolov8
classify_model: assets/tiny_resnet.onnx
yolo11_model_path: assets/yolo11.xml
yolov8_model_path: assets/yolov8.xml
yolov5_model_path: assets/yolov5.xml
device: CPU
min_confidence: 0.8
use_traditional: true

#####-----ROI-----#####
roi: 
  x: 420
  y: 50
  width: 600
  height: 600

use_roi: false

#####-----传统方法参数-----#####
threshold: 150
max_angle_error: 45 # degree
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20
min_lightbar_length: 8
min_armor_ratio: 1
max_armor_ratio: 5
max_side_ratio: 1.5
max_rectangular_error: 25 # degree

#####-----tracker参数-----#####
min_detect_count: 5
max_temp_lost_count: 15
outpost_max_temp_lost_count: 75

#####-----aimer参数-----#####
yaw_offset: -193 # degree -2.5
pitch_offset: 0 # degree 2
comming_angle: 60 # degree
leaving_angle: 20 # degree
decision_speed: 8 # rad/s
high_speed_delay_time: 0.030 # s
low_speed_delay_time: 0.015 # s

#####-----shooter参数-----#####
first_tolerance: 3 # 近距离射击容差，degree
second_tolerance: 2 # 远距离射击容差，degree
judge_distance: 2 #距离判断阈值
auto_fire: true # 是否由自瞄控制射击

camera_name: "hikrobot"
exposure_ms: 5
gain: 10.0
vid_pid: "2bdf:0001"

#  1  0  0
#  0  1  0
#  0  0  1
R_gimbal2imubody: [1, 0, 0, 0, 1, 0, 0, 0, 1]

# 重投影误差: 0.0731px
camera_matrix: [1775.8720538566968, 0, 701.31408967114066, 0, 1777.9785124633925, 526.03767946896255, 0, 0, 1]
distort_coeffs: [-0.20975581234119939, 0.16125367221132908, -0.0010892773480297192, 4.118729990412667e-05, 0]

# 相机同理想情况的偏角: yaw93.03 pitch1.73 roll-2.63 degree
# 标定板到世界坐标系原点的水平距离: 2.39 m
# 标定板同竖直摆放时的偏角: yaw-164.68 pitch7.10 roll-0.14 degree
R_camera2gimbal: [-0.99748004094852094, -0.047393736989494221, -0.052795848354845756, 0.054145309626245197, -0.027655307871428329, -0.99815002348946258, 0.045845974248730555, -0.99849337385918946, 0.030151766191677264]
t_camera2gimbal: [-0.0065665989833339922, -0.12886551013728295, 0.072349592365962945]

#####-----cboard参数-----#####
quaternion_canid: 0x100
bullet_speed_canid: 0x101
send_canid: 0xff
can_interface: "can0"

#####-----gimbal参数-----#####
com_port: "/dev/gimbal"
yaw_kp: 0
yaw_kd: 0
pitch_kp: 0
pitch_kd: 0

#####-----planner-----#####
fire_thresh: 0.0035

max_yaw_acc: 50
Q_yaw: [9e6, 0]
R_yaw: [1]

max_pitch_acc: 100
Q_pitch: [9e6, 0]
R_pitch: [1]

#####-----buff_detector参数-----#####
model: "assets/yolo11_buff_int8.xml"

#####-----buff_aimer参数-----#####
fire_gap_time: 0.700   # s
predict_time: 0.120     # s